### ISSUE TITLE
feat: Insert 함수 구현

### ISSUE THREAD

**Issue by lspc678** [OpenSourceProgramming/INHA_OSAP_004_Froyo#24]
# 👀 이슈 (issue)

Set STL에 대하여 Insert() 함수 구현

# 🚀 to-do

- [x] 새로운 노드가 삽입될 때 마다 해당 노드부터 root 노드까지 모든 노드에 대한 height를 갱신하는 기능 구현
- [x] balance factor를 구하는 함수 작성
- [x] 필요에 따라 restructuring을 수행하는 기능 구현
- [x] 새로 삽입한 노드의 depth를 구하는 함수 작성

# 📜 참고 (Restructuring 설명)

![20231128 restructuring 설명](https://github.com/OpenSourceProgramming/INHA_OSAP_004_Froyo/assets/79794123/209518c7-f493-45bd-bf41-8614bb908a18)
