### ISSUE TITLE
feat: 구글테스트 환경 구축, Insert 함수 return type 변경

### ISSUE THREAD

**Issue by lspc678** [OpenSourceProgramming/INHA_OSAP_004_Froyo#33]
# 👀 이슈 (issue)

- 구현한 Basic 기능에 대하여 구글 테스트를 이용하여 단위 테스팅을 수행할 수 있는 환경을 구축하고자 함
- 구글테스트를 원활하게 진행하기 위해 Insert() 함수의 return type을 void에서 int로 변경하고자 함

# 🚀 to-do

- [x] 구글 테스트 라이브러리를 사용할 수 있도록 CMakeList.txt 파일 내용 수정
- [x] main.cc 파일에 단위 테스팅을 할 수 있는 코드 작성
- [x] Insert() 함수의 return type을 void에서 int로 변경

**Comment by longcard** [comment]
확인했습니다!
