### ISSUE TITLE
feat: Erase 기능 구현

### ISSUE THREAD

**Issue by lspc678** [OpenSourceProgramming/INHA_OSAP_004_Froyo#44]
# 👀 이슈 (issue)

Set STL에 대하여 Erase 기능을 구현하고자 함

# 🚀 to-do

- [x] 삭제하려고 하는 노드를 찾는 기능 구현 (#43 에서 해결할 예정)
- [x] 총 3가지 경우에 대하여 노드 삭제 기능 구현
    - [x] 삭제하려고 하는 노드의 자식이 없는 경우 (EraseNodeThatHasNoChild(NodeAVL* node) 함수 구현)
    - [x] 삭제하려고 하는 노드의 자식이 1개만 있는 경우 (EraseNodeThatHasOnlyOneChild(NodeAVL* node) 함수 구현)
    - [x] 삭제하려고 하는 노드의 자식이 2개 있는 경우 (EraseNodeThatHasTwoChildren(NodeAVL* node) 함수 구현)
