### ISSUE TITLE
feat: Erase 기능 구현 (삭제하려고 하는 노드의 자식이 2개일 경우)

### ISSUE THREAD

**Issue by lspc678** [OpenSourceProgramming/INHA_OSAP_004_Froyo#47]
# 👀 이슈 (issue)

Set STL에서 삭제하려고 하는 노드의 자식이 2개일 경우에 대해 구현하고자 함 

# 🚀 to-do

- [x] EraseNodeThatHasTwoChildren(NodeAVL* node) 함수 구현
    - [x] 삭제하려고 하는 노드의 Successor를 찾는 함수 구현
    - [x] 루트 노드까지 필요에 따라 Restructuring을 진행하는 기능 구현
